image:
  file: .gitpod.dockerfile
github:
  prebuilds:
    master: true
    branches: true
    pullRequests: true
    pullRequestsFromForks: true
    addCheck: true
    addComment: true
    addBadge: true
    addLabel: true
tasks:
  - init: pub get
vscode:
  extensions:
    - dart-code.dart-code@3.19.2:aq53Ov11OfEpp/BTf5TPEA==
    - codezombiech.gitignore@0.6.0:oJP0UqwrXt2Qgt5QRm1BIQ==