name: import_amulyam_transactions
description: A sample command-line application.
# version: 1.0.0
# homepage: https://www.example.com

environment:
  sdk: '>=2.7.0 <3.0.0'

dependencies:
  html: ^0.14.0+3

dev_dependencies:
  pedantic: ^1.8.0
  test: ^1.6.0
